### ISSUE TITLE
회원가입 유효성검사 추가해주세요  -> 이승훈

### ISSUE THREAD

**Issue by HyoojinK** [RANDOMBOBS/makgol#16]
이메일 인증을 받고 이메일 칸을 수정하면 그 아이디(123이여도)로 가입이 됩니다.
그리고 비밀번호 확인 버튼을 누르지 않아도 일치하기만 하면 가입이 됩니다.
화내지마세요

**Comment by Idooru** [comment]
알겠습니당

**Comment by Idooru** [comment]
해결했습니다
