### ISSUE TITLE
여러분 각자 개인 깃허브 주소 댓글로 남겨주세요  (*^_^*)

### ISSUE THREAD

**Issue by kokoa322** [RANDOMBOBS/makgol#8]
ex) https://github.com/kokoa322

**Comment by Idooru** [comment]
이승훈 : https://github.com/Idooru

**Comment by HWoool** [comment]
김한울 : https://github.com/HWoool

**Comment by BlackLilium** [comment]
김성희 : https://github.com/BlackLilium

**Comment by BlackLilium** [comment]
김성희 : https://github.com/BlackLilium

**Comment by HyoojinK** [comment]
김효진 : https://github.com/HyoojinK
